name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  checkout:
    runs-on: ubuntu-latest

    steps:
    - name: Build Android
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: run buildozer via docker version
      run: |
          docker run --rm -v ${{ github.workspace }}:/home/user/hostcwd ghcr.io/kivy/buildozer:latest --version
    - name: recurively change the owner of /home/user/hostcwd/ to 1000:1000
      run: |
          docker run -u root --rm -v ${{ github.workspace }}:/home/user/hostcwd --entrypoint /bin/chown ghcr.io/kivy/buildozer:latest -R 1000:1000 /home/user/hostcwd/
    - name: get user id of default user from buildozer image
      run: |
          docker run --rm -v ${{ github.workspace }}:/home/user/hostcwd --entrypoint /usr/bin/id ghcr.io/kivy/buildozer:latest
    - name: run buildozer via docker
      run: |
          yes | docker run --rm -v ${{ github.workspace }}:/home/user/hostcwd ghcr.io/kivy/buildozer:latest -v android debug

    #- name: Upload APK
    #  uses: actions/upload-artifact@v4
    #  with:
    #    name: android-debug-apk
    #    path: bin/myapp-0.1-debug.apk
