name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  checkout:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

  build:
    runs-on: ubuntu-latest
    needs:
      - checkout
    container:
      image: docker://ghcr.io/kivy/buildozer:latest
      options: --user root
      volumes:
        - ${{ github.workspace }}:/home/user/hostcwd

    steps:
    - name: Build Android debug APK
      run: |
        chown -R user:user /github 
        sudo -u user python3 -m buildozer --
        sudo -u user whoami
        find /home
        sudo -u user ls /home/user/hostcwd
        sudo -u user python3 -m buildozer -v android debug
    #- name: Upload APK
    #  uses: actions/upload-artifact@v4
    #  with:
    #    name: android-debug-apk
    #    path: bin/myapp-0.1-debug.apk
